version: '3'
services:
  jupyterlab:
    build: .
    volumes:
      - "./data:/home/work"
      - ".jupyter:/root/.jupyter"
    ports:
      - "8888:8888"
    command:
      jupyter
          lab --ip=0.0.0.0
          --port=8888
          --allow-root
          --no-browser
          --NotebookApp.token=''
